//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeMage.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeMage.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close anyway に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_BUTTON_CLOSE_ANYWAY {
            get {
                return ResourceManager.GetString("DIALOG_BUTTON_CLOSE_ANYWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_BUTTON_OK {
            get {
                return ResourceManager.GetString("DIALOG_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TreeMage project file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_FILETYPE_TREEPRJ {
            get {
                return ResourceManager.GetString("DIALOG_FILETYPE_TREEPRJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_TITLE_ERROR {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_TITLE_VERIFYING {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_VERIFYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The tree format is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_INVALID_TREE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_TREE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple project files are specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_MULTIPLE_PROJECT_FILES_SPECIFIED {
            get {
                return ResourceManager.GetString("ERROR_MULTIPLE_PROJECT_FILES_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This function is supported on only Windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_SUPPORTED_ONLY_WINDOWS {
            get {
                return ResourceManager.GetString("ERROR_SUPPORTED_ONLY_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ASCENDING {
            get {
                return ResourceManager.GetString("MENU_ASCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear branch lengthes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_CLEAR_BRANCH_LENGTH {
            get {
                return ResourceManager.GetString("MENU_CLEAR_BRANCH_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear support values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_CLEAR_SUPPORT_VALUE {
            get {
                return ResourceManager.GetString("MENU_CLEAR_SUPPORT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_COLLAPSE {
            get {
                return ResourceManager.GetString("MENU_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DEBUG {
            get {
                return ResourceManager.GetString("MENU_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DESCENDING {
            get {
                return ResourceManager.GetString("MENU_DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EDIT {
            get {
                return ResourceManager.GetString("MENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit configuration(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EDIT_CONFIGURATION {
            get {
                return ResourceManager.GetString("MENU_EDIT_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EXPORT {
            get {
                return ResourceManager.GetString("MENU_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FOCUS_ALL {
            get {
                return ResourceManager.GetString("MENU_FOCUS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_HELP {
            get {
                return ResourceManager.GetString("MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Tree(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_IMPORT_TREE {
            get {
                return ResourceManager.GetString("MENU_IMPORT_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_NEW {
            get {
                return ResourceManager.GetString("MENU_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order by branch length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ORDER_BY_BRANCH_LENGTH {
            get {
                return ResourceManager.GetString("MENU_ORDER_BY_BRANCH_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo(&amp;R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_REDO {
            get {
                return ResourceManager.GetString("MENU_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Project(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_SAVE {
            get {
                return ResourceManager.GetString("MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as New Project(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_SAVE_AS {
            get {
                return ResourceManager.GetString("MENU_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Help(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_SHOW_HELP {
            get {
                return ResourceManager.GetString("MENU_SHOW_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Tree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_TREE {
            get {
                return ResourceManager.GetString("MENU_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo(&amp;U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UNDO {
            get {
                return ResourceManager.GetString("MENU_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfocus all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UNFOCUS_ALL {
            get {
                return ResourceManager.GetString("MENU_UNFOCUS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Information(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_VERSION_INFORMATION {
            get {
                return ResourceManager.GetString("MENU_VERSION_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_WINDOW {
            get {
                return ResourceManager.GetString("MENU_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsaved changes are detected. Are you sure to discard these changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_UNSAVED_CHANGES {
            get {
                return ResourceManager.GetString("WARNING_UNSAVED_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WINDOW_TITLE_EDIT_CONFIG {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_EDIT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Versions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WINDOW_TITLE_VERSIONS {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_VERSIONS", resourceCulture);
            }
        }
    }
}
