//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeMage.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeMage.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Branch decorations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_BRANCH_DECORATIONS {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_BRANCH_DECORATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Branch thickness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_BRANCH_THICKNESS {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_BRANCH_THICKNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Branch values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_BRANCH_VALUES {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_BRANCH_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clade labels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_CLADE_LABELS {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_CLADE_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_COLLAPSE_TYPE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_COLLAPSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_COLLAPSE_TYPE_WIDTH {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_COLLAPSE_TYPE_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_COLOR {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default branch length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_DEFAULT_BRANCH_LENGTH {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_DEFAULT_BRANCH_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_FONTSIZE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_FONTSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_HIDE_PATTERN {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_HIDE_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_LAYOUT {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leaf labels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_LEAF_LABELS {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_LEAF_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line thiclness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_LINE_THICKNESS {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_LINE_THICKNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Node values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_NODE_VALUES {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_NODE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_PATTERN {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SCALEBAR {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SCALEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar thickness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SCALEBAR_THICKNESS {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SCALEBAR_THICKNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SCALEBAR_VALUE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SCALEBAR_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SEARCH {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SEARCH_IGNORE_CASE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SEARCH_IGNORE_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SEARCH_TARGET {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SEARCH_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SEARCH_USE_REGEX {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SEARCH_USE_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SHAPE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_SIZE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_TREE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_VALUE_TYPE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_VALUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_XSCALE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_XSCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_EDITSIDEBAR_YSCALE {
            get {
                return ResourceManager.GetString("COMPONENT_EDITSIDEBAR_YSCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Branch color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_BRANCH_COLOR {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_BRANCH_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clade label に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_CLADE_LABEL {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_CLADE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leaf color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_LEAF_COLOR {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_LEAF_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leaf label に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_LEAF_LABEL {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_LEAF_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shade color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_SHADE_COLOR {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_SHADE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_SUPPORT_VALUE {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_SUPPORT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_TITLE {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMPONENT_STYLESIDEBAR_YSCALE {
            get {
                return ResourceManager.GetString("COMPONENT_STYLESIDEBAR_YSCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close anyway に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_BUTTON_CLOSE_ANYWAY {
            get {
                return ResourceManager.GetString("DIALOG_BUTTON_CLOSE_ANYWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_BUTTON_OK {
            get {
                return ResourceManager.GetString("DIALOG_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TreeMage project file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_FILETYPE_TREEPRJ {
            get {
                return ResourceManager.GetString("DIALOG_FILETYPE_TREEPRJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_TITLE_ERROR {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIALOG_TITLE_VERIFYING {
            get {
                return ResourceManager.GetString("DIALOG_TITLE_VERIFYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The tree format is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_INVALID_TREE_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_TREE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple project files are specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_MULTIPLE_PROJECT_FILES_SPECIFIED {
            get {
                return ResourceManager.GetString("ERROR_MULTIPLE_PROJECT_FILES_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This function is supported on only Windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_SUPPORTED_ONLY_WINDOWS {
            get {
                return ResourceManager.GetString("ERROR_SUPPORTED_ONLY_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ASCENDING {
            get {
                return ResourceManager.GetString("MENU_ASCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear branch lengthes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_CLEAR_BRANCH_LENGTH {
            get {
                return ResourceManager.GetString("MENU_CLEAR_BRANCH_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear support values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_CLEAR_SUPPORT_VALUE {
            get {
                return ResourceManager.GetString("MENU_CLEAR_SUPPORT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_COLLAPSE {
            get {
                return ResourceManager.GetString("MENU_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DEBUG {
            get {
                return ResourceManager.GetString("MENU_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DESCENDING {
            get {
                return ResourceManager.GetString("MENU_DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EDIT {
            get {
                return ResourceManager.GetString("MENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit configuration(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EDIT_CONFIGURATION {
            get {
                return ResourceManager.GetString("MENU_EDIT_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EXPORT {
            get {
                return ResourceManager.GetString("MENU_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_FOCUS_ALL {
            get {
                return ResourceManager.GetString("MENU_FOCUS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_HELP {
            get {
                return ResourceManager.GetString("MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import Tree(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_IMPORT_TREE {
            get {
                return ResourceManager.GetString("MENU_IMPORT_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_NEW {
            get {
                return ResourceManager.GetString("MENU_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order by branch length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ORDER_BY_BRANCH_LENGTH {
            get {
                return ResourceManager.GetString("MENU_ORDER_BY_BRANCH_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo(&amp;R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_REDO {
            get {
                return ResourceManager.GetString("MENU_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Project(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_SAVE {
            get {
                return ResourceManager.GetString("MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as New Project(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_SAVE_AS {
            get {
                return ResourceManager.GetString("MENU_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Help(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_SHOW_HELP {
            get {
                return ResourceManager.GetString("MENU_SHOW_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Tree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_TREE {
            get {
                return ResourceManager.GetString("MENU_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo(&amp;U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UNDO {
            get {
                return ResourceManager.GetString("MENU_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unfocus all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_UNFOCUS_ALL {
            get {
                return ResourceManager.GetString("MENU_UNFOCUS_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version Information(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_VERSION_INFORMATION {
            get {
                return ResourceManager.GetString("MENU_VERSION_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_WINDOW {
            get {
                return ResourceManager.GetString("MENU_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto ordering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGECONTENT_EDIT_CONFIG_AUTO_ORDERING {
            get {
                return ResourceManager.GetString("PAGECONTENT_EDIT_CONFIG_AUTO_ORDERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Branch coloring に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGECONTENT_EDIT_CONFIG_BRANCH_COLORING {
            get {
                return ResourceManager.GetString("PAGECONTENT_EDIT_CONFIG_BRANCH_COLORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGECONTENT_VERSIONS_DEVELOPER {
            get {
                return ResourceManager.GetString("PAGECONTENT_VERSIONS_DEVELOPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGECONTENT_VERSIONS_VERSION {
            get {
                return ResourceManager.GetString("PAGECONTENT_VERSIONS_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsaved changes are detected. Are you sure to discard these changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WARNING_UNSAVED_CHANGES {
            get {
                return ResourceManager.GetString("WARNING_UNSAVED_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Configuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WINDOW_TITLE_EDIT_CONFIG {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_EDIT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Versions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WINDOW_TITLE_VERSIONS {
            get {
                return ResourceManager.GetString("WINDOW_TITLE_VERSIONS", resourceCulture);
            }
        }
    }
}
